(define (problem grid6-6)
 (:domain floor-grid)
 ; Instantiate objects
 (:objects
  A1 A2 A3 A4 A5 A6 - grid
  B1 B2 B3 B4 B5 B6 - grid
  C1 C2 C3 C4 C5 C6 - grid
  D1 D2 D3 D4 D5 D6 - grid
  E1 E2 E3 E4 E5 E6 - grid
  robot1 robot2 robot3 robot4 - robot
  crate1 crate2 - crate
  base - radio
 )
 ; Define initial state
 (:init
  ; Horizontal connection
  (connected A1 A2) (connected A2 A1)
  (connected B1 B2) (connected B2 B1)
  (connected D1 D2) (connected D2 D1)
  (connected E1 E2) (connected E2 E1)
  (connected B2 B3) (connected B3 B2)
  (connected C2 C3) (connected C3 C2)
  (connected D2 D3) (connected D3 D2)
  (connected B3 B4) (connected B4 B3)
  (connected C3 C4) (connected C4 C3)
  (connected D3 D4) (connected D4 D3)
  (connected A4 A5) (connected A5 A4)
  (connected B4 B5) (connected B5 B4)
  (connected C4 C5) (connected C5 C4)
  (connected D4 D5) (connected D5 D4)
  (connected A5 A6) (connected A6 A5)
  (connected B5 B6) (connected B6 B5)
  (connected D5 D6) (connected D6 D5)
  (connected E5 E6) (connected E6 E5)
  ; Vertical connection
  (connected A1 B1) (connected B1 A1)
  (connected A2 B2) (connected B2 A2)
  (connected A4 B4) (connected B4 A4)
  (connected A5 B5) (connected B5 A5)
  (connected A6 B6) (connected B6 A6)
  (connected B2 C2) (connected C2 B2)
  (connected B3 C3) (connected C3 B3)
  (connected B4 C4) (connected C4 B4)
  (connected B5 C5) (connected C5 B5)
  (connected C2 D2) (connected D2 C2)
  (connected C3 D3) (connected D3 C3)
  (connected C4 D4) (connected D4 C4)
  (connected C5 D5) (connected D5 C5)
  (connected D1 E1) (connected E1 D1)
  (connected D2 E2) (connected E2 D2)
  (connected D5 E5) (connected E5 D5)
  (connected D6 E6) (connected E6 D6)
  ; Number of minimum PRBs required
 (= (prbs-required base A1) 8)
 (= (prbs-required base A2) 8)
 (= (prbs-required base A4) 6)
 (= (prbs-required base A5) 5)
 (= (prbs-required base A6) 6)
 (= (prbs-required base B1) 8)
 (= (prbs-required base B2) 8)
 (= (prbs-required base B3) 6)
 (= (prbs-required base B4) 5)
 (= (prbs-required base B5) 2)
 (= (prbs-required base B6) 5)
 (= (prbs-required base C2) 6)
 (= (prbs-required base C3) 5)
 (= (prbs-required base C4) 2)
 (= (prbs-required base C5) 1)
 (= (prbs-required base D1) 6)
 (= (prbs-required base D2) 5)
 (= (prbs-required base D3) 2)
 (= (prbs-required base D4) 1)
 (= (prbs-required base D5) 1)
 (= (prbs-required base D6) 1)
 (= (prbs-required base E1) 8)
 (= (prbs-required base E2) 6)
 (= (prbs-required base E5) 1)
 (= (prbs-required base E6) 2)
  ; Unoccupied regions
  ; (clear A1)
  (clear A2)
  ; (clear A3)
  (clear A4)
  ; (clear A5)
  (clear A6)
  ; (clear B1)
  (clear B2)
  (clear B3)
  (clear B4)
  (clear B5)
  (clear B6)
  ; (clear C1)
  (clear C2)
  (clear C3)
  ; (clear C4)
  (clear C5)
  ; (clear C6)
  (clear D1)
  (clear D2)
  (clear D3)
  (clear D4)
  (clear D5)
  (clear D6)
  (clear E1)
  (clear E2)
  ; (clear E3)
  ; (clear E4)
  (clear E5)
  (clear E6)
  ; Initialize robots
  (at-loc robot1 A1) (free robot1) (not (clear A1))
  (at-loc robot2 B1) (free robot2) (not (clear B1))
  (at-loc robot3 A5) (free robot3) (not (clear A5))
  (at-loc robot4 C4) (free robot4) (not (clear C4))
  ; Initialize crates
  (at-loc crate1 A1)
  (at-loc crate2 B1)
  ; Initialize radios
 (= (prbs-max) 32)
 (= (prbs-assigned base robot1) 8)
 (= (prbs-assigned base robot2) 8)
 (= (prbs-assigned base robot3) 5)
 (= (prbs-assigned base robot4) 2)
 (= (prbs-free base) 9)
  ; Optimization metric
  (= (total-cost) 0)
 )
 ; Objective
 (:goal (and
  (at-loc robot1 E1)
  (at-loc robot2 E2)
  (at-loc robot3 E5)
  (at-loc robot4 E6)
  (at-loc crate1 E5)
  (at-loc crate2 E6)
  )
 )
 ; Optimization
 (:metric minimize (+ (total-time) (total-cost)))
)